# frozen_string_literal: true

source 'https://rubygems.org'

# Specify your gem's dependencies in aliyun_ehpc.gemspec
gemspec

group :development, :test do
  gem 'rspec', '~> 3.12'
  gem 'rspec-mocks', '~> 3.12'
  gem 'webmock', '~> 3.18'
  gem 'vcr', '~> 6.1'
  gem 'simplecov', '~> 0.22'
  gem 'rubocop', '~> 1.50'
  gem 'rubocop-rspec', '~> 2.20'
  gem 'yard', '~> 0.9'
  gem 'redcarpet', '~> 3.6'
  gem 'pry', '~> 0.14'
  gem 'pry-byebug', '~> 3.10'
end

group :development do
  gem 'rake', '~> 13.0'
  gem 'bundler', '~> 2.4'
end
