---
v2:
  metadata:
    title: "HPC Cluster"
  login:
    host: "frontend"
  job:
    adapter: "slurm"
    cluster: "hpc"
    bin: "/usr/bin"
    conf: "/etc/slurm/slurm.conf"
  batch_connect:
    vnc:
      script_wrapper: |
        export PATH="/opt/TurboVNC/bin:$PATH"
        export WEBSOCKIFY_CMD="/usr/local/bin/websockify"
        %s
  custom:
    xdmod:
      resource_id: 1
    # MPI configuration
    mpi:
      default: "openmpi"
      implementations:
        openmpi:
          module: "mpi/openmpi"
          mpirun_cmd: "mpirun"
        mpich:
          module: "mpi/mpich"
          mpirun_cmd: "mpirun"
